"""add donation12

Revision ID: 167d1076d745
Revises: c48f2c018565
Create Date: 2023-04-06 18:51:23.887763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167d1076d745'
down_revision = 'c48f2c018565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
