"""add charityproject

Revision ID: 4beca28fbb79
Revises: 8183f34da142
Create Date: 2023-04-04 11:37:00.092452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4beca28fbb79'
down_revision = '8183f34da142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
