"""update

Revision ID: ac5bab41d1c5
Revises: 167d1076d745
Create Date: 2023-04-06 20:31:39.086808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5bab41d1c5'
down_revision = '167d1076d745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
