"""migra

Revision ID: f714c49ecdf7
Revises: 69b686a680a9
Create Date: 2023-04-05 20:35:58.582435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f714c49ecdf7'
down_revision = '69b686a680a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
